//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK5_LTHDT_BaoCaoDeTao.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-RT97DOV\\SQLEXPRESS;Initial Catalog=HK5_BaoCaoDeTai_LTHDT;Inte" +
            "grated Security=True")]
        public string HK5_BaoCaoDeTai_LTHDTConnectionString {
            get {
                return ((string)(this["HK5_BaoCaoDeTai_LTHDTConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-RT97DOV\\SQLEXPRESS;Initial Catalog=HK5_BaoCaoDeTaiCuoiKi_LTHD" +
            "T;Integrated Security=True")]
        public string HK5_BaoCaoDeTaiCuoiKi_LTHDTConnectionString {
            get {
                return ((string)(this["HK5_BaoCaoDeTaiCuoiKi_LTHDTConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-RT97DOV\\SQLEXPRESS;Initial Catalog=HK5_BaoCaoDeTaiCuoiKi_LTHD" +
            "TNC;Integrated Security=True")]
        public string HK5_BaoCaoDeTaiCuoiKi_LTHDTNCConnectionString {
            get {
                return ((string)(this["HK5_BaoCaoDeTaiCuoiKi_LTHDTNCConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-RT97DOV\\SQLEXPRESS;Initial Catalog=VD;Integrated Security=Tru" +
            "e")]
        public string VDConnectionString {
            get {
                return ((string)(this["VDConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-RT97DOV\\SQLEXPRESS;Initial Catalog=HK5_BaoCaoDeTai_QLHS;Integ" +
            "rated Security=True")]
        public string HK5_BaoCaoDeTai_QLHSConnectionString {
            get {
                return ((string)(this["HK5_BaoCaoDeTai_QLHSConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-RT97DOV\\SQLEXPRESS;Initial Catalog=HK5_BaoCaoDeTai_QLHS_nf;In" +
            "tegrated Security=True")]
        public string HK5_BaoCaoDeTai_QLHS_nfConnectionString {
            get {
                return ((string)(this["HK5_BaoCaoDeTai_QLHS_nfConnectionString"]));
            }
        }
    }
}
