#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK5_LTHDT_BaoCaoDeTao
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HK5_BaoCaoDeTai_QLHS_nf")]
	public partial class KetNoiCSDL_BaoCaoDeTaiDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertNienKhoa(NienKhoa instance);
    partial void UpdateNienKhoa(NienKhoa instance);
    partial void DeleteNienKhoa(NienKhoa instance);
    partial void InsertHocSinh(HocSinh instance);
    partial void UpdateHocSinh(HocSinh instance);
    partial void DeleteHocSinh(HocSinh instance);
    partial void InsertKhoi(Khoi instance);
    partial void UpdateKhoi(Khoi instance);
    partial void DeleteKhoi(Khoi instance);
    partial void InsertLop(Lop instance);
    partial void UpdateLop(Lop instance);
    partial void DeleteLop(Lop instance);
    partial void InsertMonHoc(MonHoc instance);
    partial void UpdateMonHoc(MonHoc instance);
    partial void DeleteMonHoc(MonHoc instance);
    #endregion
		
		public KetNoiCSDL_BaoCaoDeTaiDataContext() : 
				base(global::HK5_LTHDT_BaoCaoDeTao.Properties.Settings.Default.HK5_BaoCaoDeTai_QLHS_nfConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public KetNoiCSDL_BaoCaoDeTaiDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KetNoiCSDL_BaoCaoDeTaiDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KetNoiCSDL_BaoCaoDeTaiDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KetNoiCSDL_BaoCaoDeTaiDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BangDiemMon> BangDiemMons
		{
			get
			{
				return this.GetTable<BangDiemMon>();
			}
		}
		
		public System.Data.Linq.Table<NienKhoa> NienKhoas
		{
			get
			{
				return this.GetTable<NienKhoa>();
			}
		}
		
		public System.Data.Linq.Table<HocSinh> HocSinhs
		{
			get
			{
				return this.GetTable<HocSinh>();
			}
		}
		
		public System.Data.Linq.Table<Khoi> Khois
		{
			get
			{
				return this.GetTable<Khoi>();
			}
		}
		
		public System.Data.Linq.Table<Lop> Lops
		{
			get
			{
				return this.GetTable<Lop>();
			}
		}
		
		public System.Data.Linq.Table<MonHoc> MonHocs
		{
			get
			{
				return this.GetTable<MonHoc>();
			}
		}
		
		public System.Data.Linq.Table<NguoiDung> NguoiDungs
		{
			get
			{
				return this.GetTable<NguoiDung>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BangDiemMon_SelectAll")]
		public ISingleResult<BangDiemMon_SelectAllResult> BangDiemMon_SelectAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<BangDiemMon_SelectAllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.HocSinh_Delete")]
		public int HocSinh_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaHS", DbType="NVarChar(10)")] string maHS)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maHS);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.HocSinh_Delete")]
		public int HocSinh_Delete1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaHS", DbType="NVarChar(10)")] string maHS)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maHS);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.HocSinh_Insert")]
		public int HocSinh_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaHS", DbType="NVarChar(10)")] string maHS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenHS", DbType="NVarChar(50)")] string tenHS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaLop", DbType="NVarChar(10)")] string maLop, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GioiTinh", DbType="NVarChar(10)")] string gioiTinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SDT", DbType="NVarChar(15)")] string sDT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NgaySinh", DbType="SmallDateTime")] System.Nullable<System.DateTime> ngaySinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NoiSinh", DbType="NVarChar(50)")] string noiSinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DanToc", DbType="NVarChar(50)")] string danToc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DiaChi", DbType="NVarChar(100)")] string diaChi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maHS, tenHS, maLop, gioiTinh, sDT, ngaySinh, noiSinh, danToc, diaChi);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.HocSinh_SelectAll")]
		public ISingleResult<HocSinh_SelectAllResult> HocSinh_SelectAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<HocSinh_SelectAllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.HocSinh_SelectMaHS")]
		public ISingleResult<HocSinh_SelectMaHSResult> HocSinh_SelectMaHS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaHS", DbType="NVarChar(10)")] string maHS)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maHS);
			return ((ISingleResult<HocSinh_SelectMaHSResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.HocSinh_SelectMaLop")]
		public ISingleResult<HocSinh_SelectMaLopResult> HocSinh_SelectMaLop([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaLop", DbType="NVarChar(10)")] string maLop)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maLop);
			return ((ISingleResult<HocSinh_SelectMaLopResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.HocSinh_Update")]
		public int HocSinh_Update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaHS", DbType="NVarChar(10)")] string maHS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenHS", DbType="NVarChar(50)")] string tenHS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GioiTinh", DbType="NVarChar(10)")] string gioiTinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SDT", DbType="NVarChar(15)")] string sDT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NgaySinh", DbType="SmallDateTime")] System.Nullable<System.DateTime> ngaySinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NoiSinh", DbType="NVarChar(50)")] string noiSinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DanToc", DbType="NVarChar(50)")] string danToc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DiaChi", DbType="NVarChar(100)")] string diaChi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maHS, tenHS, gioiTinh, sDT, ngaySinh, noiSinh, danToc, diaChi);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.khoi_SelectAll")]
		public ISingleResult<khoi_SelectAllResult> khoi_SelectAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<khoi_SelectAllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Lop_Delete")]
		public int Lop_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaLop", DbType="NVarChar(10)")] string maLop)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maLop);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Lop_Insert")]
		public int Lop_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaLop", DbType="NVarChar(10)")] string maLop, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenLop", DbType="NVarChar(50)")] string tenLop, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Makhoi", DbType="NVarChar(10)")] string makhoi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaNK", DbType="NVarChar(10)")] string maNK)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maLop, tenLop, makhoi, maNK);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Lop_SelectMaNK_MaKhoi")]
		public ISingleResult<Lop_SelectMaNK_MaKhoiResult> Lop_SelectMaNK_MaKhoi([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaNK", DbType="NVarChar(10)")] string maNK, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaKhoi", DbType="NVarChar(10)")] string maKhoi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maNK, maKhoi);
			return ((ISingleResult<Lop_SelectMaNK_MaKhoiResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Lop_Update")]
		public int Lop_Update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaLop", DbType="NVarChar(10)")] string maLop, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenLop", DbType="NVarChar(50)")] string tenLop)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maLop, tenLop);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MonHoc_Delete")]
		public int MonHoc_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaMon", DbType="NVarChar(10)")] string maMon)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maMon);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MonHoc_InSert")]
		public int MonHoc_InSert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaMon", DbType="NVarChar(10)")] string maMon, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenMon", DbType="NVarChar(50)")] string tenMon)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maMon, tenMon);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MonHoc_SelectAll")]
		public ISingleResult<MonHoc_SelectAllResult> MonHoc_SelectAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<MonHoc_SelectAllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MonHoc_Update")]
		public int MonHoc_Update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaMon", DbType="NVarChar(10)")] string maMon, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenMon", DbType="NVarChar(50)")] string tenMon)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maMon, tenMon);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MonHoc_SelectMaMon")]
		public ISingleResult<MonHoc_SelectMaMonResult> MonHoc_SelectMaMon([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaMon", DbType="NVarChar(10)")] string maMon)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maMon);
			return ((ISingleResult<MonHoc_SelectMaMonResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NguoiDung_Delete")]
		public int NguoiDung_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TaiKhoan", DbType="NVarChar(50)")] string taiKhoan)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), taiKhoan);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NguoiDung_InSert")]
		public int NguoiDung_InSert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TaiKhoan", DbType="NVarChar(50)")] string taiKhoan, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MatKhat", DbType="NVarChar(50)")] string matKhat, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Quyen", DbType="NVarChar(50)")] string quyen)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), taiKhoan, matKhat, quyen);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NguoiDung_SelectAll")]
		public ISingleResult<NguoiDung_SelectAllResult> NguoiDung_SelectAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<NguoiDung_SelectAllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NguoiDung_Update")]
		public int NguoiDung_Update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TaiKhoan", DbType="NVarChar(50)")] string taiKhoan, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MatKhat", DbType="NVarChar(50)")] string matKhat, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Quyen", DbType="NVarChar(50)")] string quyen)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), taiKhoan, matKhat, quyen);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NienKhoa_Delete")]
		public int NienKhoa_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaNK", DbType="NVarChar(10)")] string maNK)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maNK);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NienKhoa_InSert")]
		public int NienKhoa_InSert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaNK", DbType="NVarChar(10)")] string maNK, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenNK", DbType="NVarChar(50)")] string tenNK)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maNK, tenNK);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NienKhoa_SelectAll")]
		public ISingleResult<NienKhoa_SelectAllResult> NienKhoa_SelectAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<NienKhoa_SelectAllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NienKhoa_Update")]
		public int NienKhoa_Update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaNK", DbType="NVarChar(10)")] string maNK, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenNK", DbType="NVarChar(50)")] string tenNK)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maNK, tenNK);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BangDiemMon_TimKiem")]
		public ISingleResult<BangDiemMon_TimKiemResult> BangDiemMon_TimKiem([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaHS", DbType="NVarChar(10)")] string maHS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaMon", DbType="NVarChar(10)")] string maMon)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maHS, maMon);
			return ((ISingleResult<BangDiemMon_TimKiemResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BangDiemMon_SelectMaMon")]
		public ISingleResult<BangDiemMon_SelectMaMonResult> BangDiemMon_SelectMaMon([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaMon", DbType="NVarChar(50)")] string maMon)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maMon);
			return ((ISingleResult<BangDiemMon_SelectMaMonResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BangDiemMon_Insert")]
		public int BangDiemMon_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaHS", DbType="NVarChar(10)")] string maHS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaMon", DbType="NVarChar(10)")] string maMon, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KTMieng", DbType="Float")] System.Nullable<double> kTMieng, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KT15L1", DbType="Float")] System.Nullable<double> kT15L1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KT15L2", DbType="Float")] System.Nullable<double> kT15L2, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KT45L1", DbType="Float")] System.Nullable<double> kT45L1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KT45L2", DbType="Float")] System.Nullable<double> kT45L2, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KTHK1", DbType="Float")] System.Nullable<double> kTHK1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KTHK2", DbType="Float")] System.Nullable<double> kTHK2)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maHS, maMon, kTMieng, kT15L1, kT15L2, kT45L1, kT45L2, kTHK1, kTHK2);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BangDiemMon_Update")]
		public int BangDiemMon_Update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaHS", DbType="NVarChar(10)")] string maHS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaMon", DbType="NVarChar(10)")] string maMon, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KTMieng", DbType="Float")] System.Nullable<double> kTMieng, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KT15L1", DbType="Float")] System.Nullable<double> kT15L1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KT15L2", DbType="Float")] System.Nullable<double> kT15L2, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KT45L1", DbType="Float")] System.Nullable<double> kT45L1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KT45L2", DbType="Float")] System.Nullable<double> kT45L2, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KTHK1", DbType="Float")] System.Nullable<double> kTHK1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KTHK2", DbType="Float")] System.Nullable<double> kTHK2)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maHS, maMon, kTMieng, kT15L1, kT15L2, kT45L1, kT45L2, kTHK1, kTHK2);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BangDiemMon")]
	public partial class BangDiemMon
	{
		
		private string _MaHS;
		
		private string _MaMon;
		
		private System.Nullable<double> _KTMieng;
		
		private System.Nullable<double> _KT15L1;
		
		private System.Nullable<double> _KT15L2;
		
		private System.Nullable<double> _KT45L1;
		
		private System.Nullable<double> _KT45L2;
		
		private System.Nullable<double> _KTHK1;
		
		private System.Nullable<double> _KTHK2;
		
		public BangDiemMon()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHS", DbType="NVarChar(10)")]
		public string MaHS
		{
			get
			{
				return this._MaHS;
			}
			set
			{
				if ((this._MaHS != value))
				{
					this._MaHS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMon", DbType="NVarChar(10)")]
		public string MaMon
		{
			get
			{
				return this._MaMon;
			}
			set
			{
				if ((this._MaMon != value))
				{
					this._MaMon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KTMieng", DbType="Float")]
		public System.Nullable<double> KTMieng
		{
			get
			{
				return this._KTMieng;
			}
			set
			{
				if ((this._KTMieng != value))
				{
					this._KTMieng = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KT15L1", DbType="Float")]
		public System.Nullable<double> KT15L1
		{
			get
			{
				return this._KT15L1;
			}
			set
			{
				if ((this._KT15L1 != value))
				{
					this._KT15L1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KT15L2", DbType="Float")]
		public System.Nullable<double> KT15L2
		{
			get
			{
				return this._KT15L2;
			}
			set
			{
				if ((this._KT15L2 != value))
				{
					this._KT15L2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KT45L1", DbType="Float")]
		public System.Nullable<double> KT45L1
		{
			get
			{
				return this._KT45L1;
			}
			set
			{
				if ((this._KT45L1 != value))
				{
					this._KT45L1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KT45L2", DbType="Float")]
		public System.Nullable<double> KT45L2
		{
			get
			{
				return this._KT45L2;
			}
			set
			{
				if ((this._KT45L2 != value))
				{
					this._KT45L2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KTHK1", DbType="Float")]
		public System.Nullable<double> KTHK1
		{
			get
			{
				return this._KTHK1;
			}
			set
			{
				if ((this._KTHK1 != value))
				{
					this._KTHK1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KTHK2", DbType="Float")]
		public System.Nullable<double> KTHK2
		{
			get
			{
				return this._KTHK2;
			}
			set
			{
				if ((this._KTHK2 != value))
				{
					this._KTHK2 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NienKhoa")]
	public partial class NienKhoa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNK;
		
		private string _TenNK;
		
		private EntitySet<Lop> _Lops;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNKChanging(string value);
    partial void OnMaNKChanged();
    partial void OnTenNKChanging(string value);
    partial void OnTenNKChanged();
    #endregion
		
		public NienKhoa()
		{
			this._Lops = new EntitySet<Lop>(new Action<Lop>(this.attach_Lops), new Action<Lop>(this.detach_Lops));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNK", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNK
		{
			get
			{
				return this._MaNK;
			}
			set
			{
				if ((this._MaNK != value))
				{
					this.OnMaNKChanging(value);
					this.SendPropertyChanging();
					this._MaNK = value;
					this.SendPropertyChanged("MaNK");
					this.OnMaNKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNK", DbType="NVarChar(50)")]
		public string TenNK
		{
			get
			{
				return this._TenNK;
			}
			set
			{
				if ((this._TenNK != value))
				{
					this.OnTenNKChanging(value);
					this.SendPropertyChanging();
					this._TenNK = value;
					this.SendPropertyChanged("TenNK");
					this.OnTenNKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NienKhoa_Lop", Storage="_Lops", ThisKey="MaNK", OtherKey="MaNK")]
		public EntitySet<Lop> Lops
		{
			get
			{
				return this._Lops;
			}
			set
			{
				this._Lops.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Lops(Lop entity)
		{
			this.SendPropertyChanging();
			entity.NienKhoa = this;
		}
		
		private void detach_Lops(Lop entity)
		{
			this.SendPropertyChanging();
			entity.NienKhoa = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HocSinh")]
	public partial class HocSinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHS;
		
		private string _TenHS;
		
		private string _MaLop;
		
		private string _GioiTinh;
		
		private string _SDT;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _NoiSinh;
		
		private string _DanToc;
		
		private string _DiaChi;
		
		private EntityRef<Lop> _Lop;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHSChanging(string value);
    partial void OnMaHSChanged();
    partial void OnTenHSChanging(string value);
    partial void OnTenHSChanged();
    partial void OnMaLopChanging(string value);
    partial void OnMaLopChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnNoiSinhChanging(string value);
    partial void OnNoiSinhChanged();
    partial void OnDanTocChanging(string value);
    partial void OnDanTocChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    #endregion
		
		public HocSinh()
		{
			this._Lop = default(EntityRef<Lop>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHS", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHS
		{
			get
			{
				return this._MaHS;
			}
			set
			{
				if ((this._MaHS != value))
				{
					this.OnMaHSChanging(value);
					this.SendPropertyChanging();
					this._MaHS = value;
					this.SendPropertyChanged("MaHS");
					this.OnMaHSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHS", DbType="NVarChar(50)")]
		public string TenHS
		{
			get
			{
				return this._TenHS;
			}
			set
			{
				if ((this._TenHS != value))
				{
					this.OnTenHSChanging(value);
					this.SendPropertyChanging();
					this._TenHS = value;
					this.SendPropertyChanged("TenHS");
					this.OnTenHSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLop", DbType="NVarChar(10)")]
		public string MaLop
		{
			get
			{
				return this._MaLop;
			}
			set
			{
				if ((this._MaLop != value))
				{
					if (this._Lop.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLopChanging(value);
					this.SendPropertyChanging();
					this._MaLop = value;
					this.SendPropertyChanged("MaLop");
					this.OnMaLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(10)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(15)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiSinh", DbType="NVarChar(50)")]
		public string NoiSinh
		{
			get
			{
				return this._NoiSinh;
			}
			set
			{
				if ((this._NoiSinh != value))
				{
					this.OnNoiSinhChanging(value);
					this.SendPropertyChanging();
					this._NoiSinh = value;
					this.SendPropertyChanged("NoiSinh");
					this.OnNoiSinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanToc", DbType="NVarChar(50)")]
		public string DanToc
		{
			get
			{
				return this._DanToc;
			}
			set
			{
				if ((this._DanToc != value))
				{
					this.OnDanTocChanging(value);
					this.SendPropertyChanging();
					this._DanToc = value;
					this.SendPropertyChanged("DanToc");
					this.OnDanTocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(100)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Lop_HocSinh", Storage="_Lop", ThisKey="MaLop", OtherKey="MaLop", IsForeignKey=true)]
		public Lop Lop
		{
			get
			{
				return this._Lop.Entity;
			}
			set
			{
				Lop previousValue = this._Lop.Entity;
				if (((previousValue != value) 
							|| (this._Lop.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Lop.Entity = null;
						previousValue.HocSinhs.Remove(this);
					}
					this._Lop.Entity = value;
					if ((value != null))
					{
						value.HocSinhs.Add(this);
						this._MaLop = value.MaLop;
					}
					else
					{
						this._MaLop = default(string);
					}
					this.SendPropertyChanged("Lop");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Khoi")]
	public partial class Khoi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKhoi;
		
		private string _TenKhoi;
		
		private EntitySet<Lop> _Lops;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhoiChanging(string value);
    partial void OnMaKhoiChanged();
    partial void OnTenKhoiChanging(string value);
    partial void OnTenKhoiChanged();
    #endregion
		
		public Khoi()
		{
			this._Lops = new EntitySet<Lop>(new Action<Lop>(this.attach_Lops), new Action<Lop>(this.detach_Lops));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhoi", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKhoi
		{
			get
			{
				return this._MaKhoi;
			}
			set
			{
				if ((this._MaKhoi != value))
				{
					this.OnMaKhoiChanging(value);
					this.SendPropertyChanging();
					this._MaKhoi = value;
					this.SendPropertyChanged("MaKhoi");
					this.OnMaKhoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhoi", DbType="NVarChar(50)")]
		public string TenKhoi
		{
			get
			{
				return this._TenKhoi;
			}
			set
			{
				if ((this._TenKhoi != value))
				{
					this.OnTenKhoiChanging(value);
					this.SendPropertyChanging();
					this._TenKhoi = value;
					this.SendPropertyChanged("TenKhoi");
					this.OnTenKhoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khoi_Lop", Storage="_Lops", ThisKey="MaKhoi", OtherKey="Makhoi")]
		public EntitySet<Lop> Lops
		{
			get
			{
				return this._Lops;
			}
			set
			{
				this._Lops.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Lops(Lop entity)
		{
			this.SendPropertyChanging();
			entity.Khoi = this;
		}
		
		private void detach_Lops(Lop entity)
		{
			this.SendPropertyChanging();
			entity.Khoi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Lop")]
	public partial class Lop : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLop;
		
		private string _TenLop;
		
		private string _Makhoi;
		
		private string _MaNK;
		
		private EntitySet<HocSinh> _HocSinhs;
		
		private EntityRef<Khoi> _Khoi;
		
		private EntityRef<NienKhoa> _NienKhoa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLopChanging(string value);
    partial void OnMaLopChanged();
    partial void OnTenLopChanging(string value);
    partial void OnTenLopChanged();
    partial void OnMakhoiChanging(string value);
    partial void OnMakhoiChanged();
    partial void OnMaNKChanging(string value);
    partial void OnMaNKChanged();
    #endregion
		
		public Lop()
		{
			this._HocSinhs = new EntitySet<HocSinh>(new Action<HocSinh>(this.attach_HocSinhs), new Action<HocSinh>(this.detach_HocSinhs));
			this._Khoi = default(EntityRef<Khoi>);
			this._NienKhoa = default(EntityRef<NienKhoa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLop", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLop
		{
			get
			{
				return this._MaLop;
			}
			set
			{
				if ((this._MaLop != value))
				{
					this.OnMaLopChanging(value);
					this.SendPropertyChanging();
					this._MaLop = value;
					this.SendPropertyChanged("MaLop");
					this.OnMaLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLop", DbType="NVarChar(50)")]
		public string TenLop
		{
			get
			{
				return this._TenLop;
			}
			set
			{
				if ((this._TenLop != value))
				{
					this.OnTenLopChanging(value);
					this.SendPropertyChanging();
					this._TenLop = value;
					this.SendPropertyChanged("TenLop");
					this.OnTenLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Makhoi", DbType="NVarChar(10)")]
		public string Makhoi
		{
			get
			{
				return this._Makhoi;
			}
			set
			{
				if ((this._Makhoi != value))
				{
					if (this._Khoi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMakhoiChanging(value);
					this.SendPropertyChanging();
					this._Makhoi = value;
					this.SendPropertyChanged("Makhoi");
					this.OnMakhoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNK", DbType="NVarChar(10)")]
		public string MaNK
		{
			get
			{
				return this._MaNK;
			}
			set
			{
				if ((this._MaNK != value))
				{
					if (this._NienKhoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNKChanging(value);
					this.SendPropertyChanging();
					this._MaNK = value;
					this.SendPropertyChanged("MaNK");
					this.OnMaNKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Lop_HocSinh", Storage="_HocSinhs", ThisKey="MaLop", OtherKey="MaLop")]
		public EntitySet<HocSinh> HocSinhs
		{
			get
			{
				return this._HocSinhs;
			}
			set
			{
				this._HocSinhs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khoi_Lop", Storage="_Khoi", ThisKey="Makhoi", OtherKey="MaKhoi", IsForeignKey=true)]
		public Khoi Khoi
		{
			get
			{
				return this._Khoi.Entity;
			}
			set
			{
				Khoi previousValue = this._Khoi.Entity;
				if (((previousValue != value) 
							|| (this._Khoi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Khoi.Entity = null;
						previousValue.Lops.Remove(this);
					}
					this._Khoi.Entity = value;
					if ((value != null))
					{
						value.Lops.Add(this);
						this._Makhoi = value.MaKhoi;
					}
					else
					{
						this._Makhoi = default(string);
					}
					this.SendPropertyChanged("Khoi");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NienKhoa_Lop", Storage="_NienKhoa", ThisKey="MaNK", OtherKey="MaNK", IsForeignKey=true)]
		public NienKhoa NienKhoa
		{
			get
			{
				return this._NienKhoa.Entity;
			}
			set
			{
				NienKhoa previousValue = this._NienKhoa.Entity;
				if (((previousValue != value) 
							|| (this._NienKhoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NienKhoa.Entity = null;
						previousValue.Lops.Remove(this);
					}
					this._NienKhoa.Entity = value;
					if ((value != null))
					{
						value.Lops.Add(this);
						this._MaNK = value.MaNK;
					}
					else
					{
						this._MaNK = default(string);
					}
					this.SendPropertyChanged("NienKhoa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HocSinhs(HocSinh entity)
		{
			this.SendPropertyChanging();
			entity.Lop = this;
		}
		
		private void detach_HocSinhs(HocSinh entity)
		{
			this.SendPropertyChanging();
			entity.Lop = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MonHoc")]
	public partial class MonHoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaMon;
		
		private string _TenMon;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaMonChanging(string value);
    partial void OnMaMonChanged();
    partial void OnTenMonChanging(string value);
    partial void OnTenMonChanged();
    #endregion
		
		public MonHoc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMon", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaMon
		{
			get
			{
				return this._MaMon;
			}
			set
			{
				if ((this._MaMon != value))
				{
					this.OnMaMonChanging(value);
					this.SendPropertyChanging();
					this._MaMon = value;
					this.SendPropertyChanged("MaMon");
					this.OnMaMonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMon", DbType="NVarChar(50)")]
		public string TenMon
		{
			get
			{
				return this._TenMon;
			}
			set
			{
				if ((this._TenMon != value))
				{
					this.OnTenMonChanging(value);
					this.SendPropertyChanging();
					this._TenMon = value;
					this.SendPropertyChanged("TenMon");
					this.OnTenMonChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NguoiDung")]
	public partial class NguoiDung
	{
		
		private string _TaiKhoan;
		
		private string _MatKhat;
		
		private string _Quyen;
		
		public NguoiDung()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoan", DbType="NVarChar(50)")]
		public string TaiKhoan
		{
			get
			{
				return this._TaiKhoan;
			}
			set
			{
				if ((this._TaiKhoan != value))
				{
					this._TaiKhoan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhat", DbType="NVarChar(50)")]
		public string MatKhat
		{
			get
			{
				return this._MatKhat;
			}
			set
			{
				if ((this._MatKhat != value))
				{
					this._MatKhat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quyen", DbType="NVarChar(50)")]
		public string Quyen
		{
			get
			{
				return this._Quyen;
			}
			set
			{
				if ((this._Quyen != value))
				{
					this._Quyen = value;
				}
			}
		}
	}
	
	public partial class BangDiemMon_SelectAllResult
	{
		
		private string _MaHS;
		
		private string _MaMon;
		
		private System.Nullable<double> _KTMieng;
		
		private System.Nullable<double> _KT15L1;
		
		private System.Nullable<double> _KT15L2;
		
		private System.Nullable<double> _KT45L1;
		
		private System.Nullable<double> _KT45L2;
		
		private System.Nullable<double> _KTHK1;
		
		private System.Nullable<double> _KTHK2;
		
		public BangDiemMon_SelectAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHS", DbType="NVarChar(10)")]
		public string MaHS
		{
			get
			{
				return this._MaHS;
			}
			set
			{
				if ((this._MaHS != value))
				{
					this._MaHS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMon", DbType="NVarChar(10)")]
		public string MaMon
		{
			get
			{
				return this._MaMon;
			}
			set
			{
				if ((this._MaMon != value))
				{
					this._MaMon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KTMieng", DbType="Float")]
		public System.Nullable<double> KTMieng
		{
			get
			{
				return this._KTMieng;
			}
			set
			{
				if ((this._KTMieng != value))
				{
					this._KTMieng = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KT15L1", DbType="Float")]
		public System.Nullable<double> KT15L1
		{
			get
			{
				return this._KT15L1;
			}
			set
			{
				if ((this._KT15L1 != value))
				{
					this._KT15L1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KT15L2", DbType="Float")]
		public System.Nullable<double> KT15L2
		{
			get
			{
				return this._KT15L2;
			}
			set
			{
				if ((this._KT15L2 != value))
				{
					this._KT15L2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KT45L1", DbType="Float")]
		public System.Nullable<double> KT45L1
		{
			get
			{
				return this._KT45L1;
			}
			set
			{
				if ((this._KT45L1 != value))
				{
					this._KT45L1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KT45L2", DbType="Float")]
		public System.Nullable<double> KT45L2
		{
			get
			{
				return this._KT45L2;
			}
			set
			{
				if ((this._KT45L2 != value))
				{
					this._KT45L2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KTHK1", DbType="Float")]
		public System.Nullable<double> KTHK1
		{
			get
			{
				return this._KTHK1;
			}
			set
			{
				if ((this._KTHK1 != value))
				{
					this._KTHK1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KTHK2", DbType="Float")]
		public System.Nullable<double> KTHK2
		{
			get
			{
				return this._KTHK2;
			}
			set
			{
				if ((this._KTHK2 != value))
				{
					this._KTHK2 = value;
				}
			}
		}
	}
	
	public partial class HocSinh_SelectAllResult
	{
		
		private string _MaHS;
		
		private string _TenHS;
		
		private string _MaLop;
		
		private string _GioiTinh;
		
		private string _SDT;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _NoiSinh;
		
		private string _DanToc;
		
		private string _DiaChi;
		
		public HocSinh_SelectAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHS", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string MaHS
		{
			get
			{
				return this._MaHS;
			}
			set
			{
				if ((this._MaHS != value))
				{
					this._MaHS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHS", DbType="NVarChar(50)")]
		public string TenHS
		{
			get
			{
				return this._TenHS;
			}
			set
			{
				if ((this._TenHS != value))
				{
					this._TenHS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLop", DbType="NVarChar(10)")]
		public string MaLop
		{
			get
			{
				return this._MaLop;
			}
			set
			{
				if ((this._MaLop != value))
				{
					this._MaLop = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(10)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this._GioiTinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(15)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this._SDT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this._NgaySinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiSinh", DbType="NVarChar(50)")]
		public string NoiSinh
		{
			get
			{
				return this._NoiSinh;
			}
			set
			{
				if ((this._NoiSinh != value))
				{
					this._NoiSinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanToc", DbType="NVarChar(50)")]
		public string DanToc
		{
			get
			{
				return this._DanToc;
			}
			set
			{
				if ((this._DanToc != value))
				{
					this._DanToc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(100)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this._DiaChi = value;
				}
			}
		}
	}
	
	public partial class HocSinh_SelectMaHSResult
	{
		
		private string _MaHS;
		
		private string _TenHS;
		
		private string _MaLop;
		
		private string _GioiTinh;
		
		private string _SDT;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _NoiSinh;
		
		private string _DanToc;
		
		private string _DiaChi;
		
		public HocSinh_SelectMaHSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHS", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string MaHS
		{
			get
			{
				return this._MaHS;
			}
			set
			{
				if ((this._MaHS != value))
				{
					this._MaHS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHS", DbType="NVarChar(50)")]
		public string TenHS
		{
			get
			{
				return this._TenHS;
			}
			set
			{
				if ((this._TenHS != value))
				{
					this._TenHS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLop", DbType="NVarChar(10)")]
		public string MaLop
		{
			get
			{
				return this._MaLop;
			}
			set
			{
				if ((this._MaLop != value))
				{
					this._MaLop = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(10)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this._GioiTinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(15)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this._SDT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this._NgaySinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiSinh", DbType="NVarChar(50)")]
		public string NoiSinh
		{
			get
			{
				return this._NoiSinh;
			}
			set
			{
				if ((this._NoiSinh != value))
				{
					this._NoiSinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanToc", DbType="NVarChar(50)")]
		public string DanToc
		{
			get
			{
				return this._DanToc;
			}
			set
			{
				if ((this._DanToc != value))
				{
					this._DanToc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(100)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this._DiaChi = value;
				}
			}
		}
	}
	
	public partial class HocSinh_SelectMaLopResult
	{
		
		private string _MaHS;
		
		private string _TenHS;
		
		private string _MaLop;
		
		private string _GioiTinh;
		
		private string _SDT;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _NoiSinh;
		
		private string _DanToc;
		
		private string _DiaChi;
		
		public HocSinh_SelectMaLopResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHS", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string MaHS
		{
			get
			{
				return this._MaHS;
			}
			set
			{
				if ((this._MaHS != value))
				{
					this._MaHS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHS", DbType="NVarChar(50)")]
		public string TenHS
		{
			get
			{
				return this._TenHS;
			}
			set
			{
				if ((this._TenHS != value))
				{
					this._TenHS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLop", DbType="NVarChar(10)")]
		public string MaLop
		{
			get
			{
				return this._MaLop;
			}
			set
			{
				if ((this._MaLop != value))
				{
					this._MaLop = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(10)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this._GioiTinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(15)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this._SDT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this._NgaySinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiSinh", DbType="NVarChar(50)")]
		public string NoiSinh
		{
			get
			{
				return this._NoiSinh;
			}
			set
			{
				if ((this._NoiSinh != value))
				{
					this._NoiSinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanToc", DbType="NVarChar(50)")]
		public string DanToc
		{
			get
			{
				return this._DanToc;
			}
			set
			{
				if ((this._DanToc != value))
				{
					this._DanToc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(100)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this._DiaChi = value;
				}
			}
		}
	}
	
	public partial class khoi_SelectAllResult
	{
		
		private string _MaKhoi;
		
		private string _TenKhoi;
		
		public khoi_SelectAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhoi", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string MaKhoi
		{
			get
			{
				return this._MaKhoi;
			}
			set
			{
				if ((this._MaKhoi != value))
				{
					this._MaKhoi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhoi", DbType="NVarChar(50)")]
		public string TenKhoi
		{
			get
			{
				return this._TenKhoi;
			}
			set
			{
				if ((this._TenKhoi != value))
				{
					this._TenKhoi = value;
				}
			}
		}
	}
	
	public partial class Lop_SelectMaNK_MaKhoiResult
	{
		
		private string _MaLop;
		
		private string _TenLop;
		
		private string _Makhoi;
		
		private string _MaNK;
		
		public Lop_SelectMaNK_MaKhoiResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLop", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string MaLop
		{
			get
			{
				return this._MaLop;
			}
			set
			{
				if ((this._MaLop != value))
				{
					this._MaLop = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLop", DbType="NVarChar(50)")]
		public string TenLop
		{
			get
			{
				return this._TenLop;
			}
			set
			{
				if ((this._TenLop != value))
				{
					this._TenLop = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Makhoi", DbType="NVarChar(10)")]
		public string Makhoi
		{
			get
			{
				return this._Makhoi;
			}
			set
			{
				if ((this._Makhoi != value))
				{
					this._Makhoi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNK", DbType="NVarChar(10)")]
		public string MaNK
		{
			get
			{
				return this._MaNK;
			}
			set
			{
				if ((this._MaNK != value))
				{
					this._MaNK = value;
				}
			}
		}
	}
	
	public partial class MonHoc_SelectAllResult
	{
		
		private string _MaMon;
		
		private string _TenMon;
		
		public MonHoc_SelectAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMon", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string MaMon
		{
			get
			{
				return this._MaMon;
			}
			set
			{
				if ((this._MaMon != value))
				{
					this._MaMon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMon", DbType="NVarChar(50)")]
		public string TenMon
		{
			get
			{
				return this._TenMon;
			}
			set
			{
				if ((this._TenMon != value))
				{
					this._TenMon = value;
				}
			}
		}
	}
	
	public partial class MonHoc_SelectMaMonResult
	{
		
		private string _MaMon;
		
		private string _TenMon;
		
		public MonHoc_SelectMaMonResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMon", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string MaMon
		{
			get
			{
				return this._MaMon;
			}
			set
			{
				if ((this._MaMon != value))
				{
					this._MaMon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMon", DbType="NVarChar(50)")]
		public string TenMon
		{
			get
			{
				return this._TenMon;
			}
			set
			{
				if ((this._TenMon != value))
				{
					this._TenMon = value;
				}
			}
		}
	}
	
	public partial class NguoiDung_SelectAllResult
	{
		
		private string _TaiKhoan;
		
		private string _MatKhat;
		
		private string _Quyen;
		
		public NguoiDung_SelectAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoan", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TaiKhoan
		{
			get
			{
				return this._TaiKhoan;
			}
			set
			{
				if ((this._TaiKhoan != value))
				{
					this._TaiKhoan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhat", DbType="NVarChar(50)")]
		public string MatKhat
		{
			get
			{
				return this._MatKhat;
			}
			set
			{
				if ((this._MatKhat != value))
				{
					this._MatKhat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quyen", DbType="NVarChar(50)")]
		public string Quyen
		{
			get
			{
				return this._Quyen;
			}
			set
			{
				if ((this._Quyen != value))
				{
					this._Quyen = value;
				}
			}
		}
	}
	
	public partial class NienKhoa_SelectAllResult
	{
		
		private string _MaNK;
		
		private string _TenNK;
		
		public NienKhoa_SelectAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNK", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string MaNK
		{
			get
			{
				return this._MaNK;
			}
			set
			{
				if ((this._MaNK != value))
				{
					this._MaNK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNK", DbType="NVarChar(50)")]
		public string TenNK
		{
			get
			{
				return this._TenNK;
			}
			set
			{
				if ((this._TenNK != value))
				{
					this._TenNK = value;
				}
			}
		}
	}
	
	public partial class BangDiemMon_TimKiemResult
	{
		
		private string _MaHS;
		
		private string _MaMon;
		
		private System.Nullable<double> _KTMieng;
		
		private System.Nullable<double> _KT15L1;
		
		private System.Nullable<double> _KT15L2;
		
		private System.Nullable<double> _KT45L1;
		
		private System.Nullable<double> _KT45L2;
		
		private System.Nullable<double> _KTHK1;
		
		private System.Nullable<double> _KTHK2;
		
		public BangDiemMon_TimKiemResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHS", DbType="NVarChar(10)")]
		public string MaHS
		{
			get
			{
				return this._MaHS;
			}
			set
			{
				if ((this._MaHS != value))
				{
					this._MaHS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMon", DbType="NVarChar(10)")]
		public string MaMon
		{
			get
			{
				return this._MaMon;
			}
			set
			{
				if ((this._MaMon != value))
				{
					this._MaMon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KTMieng", DbType="Float")]
		public System.Nullable<double> KTMieng
		{
			get
			{
				return this._KTMieng;
			}
			set
			{
				if ((this._KTMieng != value))
				{
					this._KTMieng = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KT15L1", DbType="Float")]
		public System.Nullable<double> KT15L1
		{
			get
			{
				return this._KT15L1;
			}
			set
			{
				if ((this._KT15L1 != value))
				{
					this._KT15L1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KT15L2", DbType="Float")]
		public System.Nullable<double> KT15L2
		{
			get
			{
				return this._KT15L2;
			}
			set
			{
				if ((this._KT15L2 != value))
				{
					this._KT15L2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KT45L1", DbType="Float")]
		public System.Nullable<double> KT45L1
		{
			get
			{
				return this._KT45L1;
			}
			set
			{
				if ((this._KT45L1 != value))
				{
					this._KT45L1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KT45L2", DbType="Float")]
		public System.Nullable<double> KT45L2
		{
			get
			{
				return this._KT45L2;
			}
			set
			{
				if ((this._KT45L2 != value))
				{
					this._KT45L2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KTHK1", DbType="Float")]
		public System.Nullable<double> KTHK1
		{
			get
			{
				return this._KTHK1;
			}
			set
			{
				if ((this._KTHK1 != value))
				{
					this._KTHK1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KTHK2", DbType="Float")]
		public System.Nullable<double> KTHK2
		{
			get
			{
				return this._KTHK2;
			}
			set
			{
				if ((this._KTHK2 != value))
				{
					this._KTHK2 = value;
				}
			}
		}
	}
	
	public partial class BangDiemMon_SelectMaMonResult
	{
		
		private string _MaHS;
		
		private string _MaMon;
		
		private System.Nullable<double> _KTMieng;
		
		private System.Nullable<double> _KT15L1;
		
		private System.Nullable<double> _KT15L2;
		
		private System.Nullable<double> _KT45L1;
		
		private System.Nullable<double> _KT45L2;
		
		private System.Nullable<double> _KTHK1;
		
		private System.Nullable<double> _KTHK2;
		
		public BangDiemMon_SelectMaMonResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHS", DbType="NVarChar(10)")]
		public string MaHS
		{
			get
			{
				return this._MaHS;
			}
			set
			{
				if ((this._MaHS != value))
				{
					this._MaHS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMon", DbType="NVarChar(10)")]
		public string MaMon
		{
			get
			{
				return this._MaMon;
			}
			set
			{
				if ((this._MaMon != value))
				{
					this._MaMon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KTMieng", DbType="Float")]
		public System.Nullable<double> KTMieng
		{
			get
			{
				return this._KTMieng;
			}
			set
			{
				if ((this._KTMieng != value))
				{
					this._KTMieng = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KT15L1", DbType="Float")]
		public System.Nullable<double> KT15L1
		{
			get
			{
				return this._KT15L1;
			}
			set
			{
				if ((this._KT15L1 != value))
				{
					this._KT15L1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KT15L2", DbType="Float")]
		public System.Nullable<double> KT15L2
		{
			get
			{
				return this._KT15L2;
			}
			set
			{
				if ((this._KT15L2 != value))
				{
					this._KT15L2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KT45L1", DbType="Float")]
		public System.Nullable<double> KT45L1
		{
			get
			{
				return this._KT45L1;
			}
			set
			{
				if ((this._KT45L1 != value))
				{
					this._KT45L1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KT45L2", DbType="Float")]
		public System.Nullable<double> KT45L2
		{
			get
			{
				return this._KT45L2;
			}
			set
			{
				if ((this._KT45L2 != value))
				{
					this._KT45L2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KTHK1", DbType="Float")]
		public System.Nullable<double> KTHK1
		{
			get
			{
				return this._KTHK1;
			}
			set
			{
				if ((this._KTHK1 != value))
				{
					this._KTHK1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KTHK2", DbType="Float")]
		public System.Nullable<double> KTHK2
		{
			get
			{
				return this._KTHK2;
			}
			set
			{
				if ((this._KTHK2 != value))
				{
					this._KTHK2 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
